### PR TITLE
I'd like to be added to this repo

### PR DESCRIPTION
**Pull request by tim4242**
I'd like to add this (unfinished) program to the MiscPrograms repository

### CODE REVIEW

**Comment by Vexatos** [comment]
Should I merge it now or should I wait until it is done?

**Comment by tim4242** [comment]
If there is a policy that prohibits incomplete programs then pleace close this if not then pleace merge it.

**Comment by tim4242** [comment]
Sorry for wasting your time, I will work a little more on it until it is representable. Thanks for your time.

**Comment by Vexatos** [comment]
Well you could just have pushed your changes to the same branch and they would appear on this Pull Request, I would just have left it open until you told me it was ready.

**Comment by tim4242** [comment]
Now I would like to be added to the repo, if it is still possible.

**Pull request merged**
